package com.crcl.authentication.utils;

public interface DefaultPermissions {

    // PERMISSION FOR BUY
    String PERMISSION_BUY_READ = "PERMISSION_BUY_READ";
    String PERMISSION_BUY_WRITE = "PERMISSION_BUY_WRITE";
    String PERMISSION_BUY_DELETE = "PERMISSION_BUY_DELETE";
    String PERMISSION_BUY_MODIFY = "PERMISSION_BUY_MODIFY";
    String PERMISSION_BUY_VIEW = "PERMISSION_BUY_VIEW";
    // PERMISSION FOR CALL
    String PERMISSION_CALL_READ = "PERMISSION_CALL_READ";
    String PERMISSION_CALL_WRITE = "PERMISSION_CALL_WRITE";
    String PERMISSION_CALL_DELETE = "PERMISSION_CALL_DELETE";
    String PERMISSION_CALL_MODIFY = "PERMISSION_CALL_MODIFY";
    String PERMISSION_CALL_VIEW = "PERMISSION_CALL_VIEW";
    // PERMISSION FOR TAG
    String PERMISSION_TAG_READ = "PERMISSION_TAG_READ";
    String PERMISSION_TAG_WRITE = "PERMISSION_TAG_WRITE";
    String PERMISSION_TAG_DELETE = "PERMISSION_TAG_DELETE";
    String PERMISSION_TAG_MODIFY = "PERMISSION_TAG_MODIFY";
    String PERMISSION_TAG_VIEW = "PERMISSION_TAG_VIEW";
    // PERMISSION FOR POST
    String PERMISSION_POST_READ = "PERMISSION_POST_READ";
    String PERMISSION_POST_WRITE = "PERMISSION_POST_WRITE";
    String PERMISSION_POST_DELETE = "PERMISSION_POST_DELETE";
    String PERMISSION_POST_MODIFY = "PERMISSION_POST_MODIFY";
    String PERMISSION_POST_VIEW = "PERMISSION_POST_VIEW";
    // PERMISSION FOR COMMENT
    String PERMISSION_COMMENT_READ = "PERMISSION_COMMENT_READ";
    String PERMISSION_COMMENT_WRITE = "PERMISSION_COMMENT_WRITE";
    String PERMISSION_COMMENT_DELETE = "PERMISSION_COMMENT_DELETE";
    String PERMISSION_COMMENT_MODIFY = "PERMISSION_COMMENT_MODIFY";
    String PERMISSION_COMMENT_VIEW = "PERMISSION_COMMENT_VIEW";
    // PERMISSION FOR LIKE
    String PERMISSION_LIKE_READ = "PERMISSION_LIKE_READ";
    String PERMISSION_LIKE_WRITE = "PERMISSION_LIKE_WRITE";
    String PERMISSION_LIKE_DELETE = "PERMISSION_LIKE_DELETE";
    String PERMISSION_LIKE_MODIFY = "PERMISSION_LIKE_MODIFY";
    String PERMISSION_LIKE_VIEW = "PERMISSION_LIKE_VIEW";
    // PERMISSION FOR FRIEND
    String PERMISSION_FRIEND_READ = "PERMISSION_FRIEND_READ";
    String PERMISSION_FRIEND_WRITE = "PERMISSION_FRIEND_WRITE";
    String PERMISSION_FRIEND_DELETE = "PERMISSION_FRIEND_DELETE";
    String PERMISSION_FRIEND_MODIFY = "PERMISSION_FRIEND_MODIFY";
    String PERMISSION_FRIEND_VIEW = "PERMISSION_FRIEND_VIEW";
}
