variables:
  MODULE_NAME: storage-service

.changes:
  only:
    changes:
      - .gitlab-ci-storage-service.yml
      - $MODULE_NAME/**
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

storage-service-build:
  extends:
    - .build

storage-service-docker:
  extends:
    - .docker

storage-service-deploy:
  extends:
    - .deploy
