# Update n.0
.changes:
  only:
    changes:
      - $MODULE_NAME/**
      - .gitlab-ci-post-service.yml
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

post-service-build:
  variables:
    MODULE_NAME: post-service
  extends:
    - .build

post-service-docker:
  variables:
    MODULE_NAME: post-service
  extends:
    - .docker

post-service-deploy:
  variables:
    MODULE_NAME: post-service
  extends:
    - .deploy

