# Update n.0
.changes:
  only:
    changes:
      - $MODULE_NAME/**
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

common-build:
  variables:
    MODULE_NAME: common
  extends:
    - .build
  script:
    - mvn -s settings.xml -Dmaven.repo.local=.m2/repository -DskipTests=true deploy -pl $MODULE_NAME

