stages:
  - test
.test_template: &test_suite
  stage: test
  image: ruby:2.6

unit_test:
  <<: *test_suite
  script:
    - echo "Running a test here"

end_to_end_test:
  <<: *test_suite
  script:
    - echo "Running a test here"

smoke_test:
  <<: *test_suite
  script:
    - echo "Running a test here"
