stages:
  - build
  - docker
  - deploy

.changes:
  only:
    changes:
      - .gitlab-ci.yml

build-maven:
  stage: maven
  image:
    name: nginx
    pull_policy: if-not-present
  script:
    - echo "HELLO WORLD !!!"

build-docker:
  stage: docker
  image:
    name: nginx
    pull_policy: if-not-present
  script:
    - echo "HELLO WORLD !!!"

deploy-compose:
  stage: deploy
  image:
    name: nginx
    pull_policy: if-not-present
  script:
    - echo "HELLO WORLD !!!"

deploy-k8s:
  stage: deploy
  image:
    name: nginx
    pull_policy: if-not-present
  script:
    - echo "HELLO WORLD !!!"

