services:
  - name: docker:latest

.changes:
  only:
    - pushes
    - triggers

stages:
  - maven
  - docker
  - deploy

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: ""
  MAVEN_CLI_OPTS: ""

maven:
  extends:
    - .changes
  stage: maven
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DskipTests=true clean package
  artifacts:
    paths:
      - target/*
  tags:
    - dev

docker:
  extends:
    - .changes
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:$CI_COMMIT_SHORT_SHA"
  tags:
    - dev

deploy:
  extends:
    - .changes
  image: bitnami/kubectl:latest
  stage: deploy
  script:
    - sed -i "s/latest/$CI_COMMIT_SHORT_SHA/g" "k8s-client-deployment.yaml"
    - kubectl apply -f k8s-client-deployment.yaml
  tags:
    - dev