# 1
stages:
  - maven
  - docker
  - deploy
cache:
  paths:
    - .m2/repository

.build:
  before_script:
    - echo "Start build $MODULE_NAME"
    - |
      cat <<EOF > settings.xml
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
              <server>
                  <id>gitlab-registry</id>
                  <username>${CI_REGISTRY_USER}</username>
                  <password>${CI_REGISTRY_PASSWORD}</password>
              </server>
          </servers>
      </settings>
      EOF
  extends:
    - .changes
  stage: maven
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -s settings.xml -Dmaven.repo.local=.m2/repository -DskipTests=true deploy -pl $MODULE_NAME
  tags:
    - dev
  when: manual

.docker:
  extends:
    - .changes
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/$MODULE_NAME/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA"
  tags:
    - dev
  when: manual

.deploy:
  extends:
    - .changes
  stage: deploy
  script:
    - if [ "$CI_PIPELINE_SOURCE" == "push" ] && git diff --name-only $CI_COMMIT_BEFORE_SHA..$CI_COMMIT_REF_NAME | grep --quiet module1/; then
      cd $MODULE_NAME;
      ls
      else
      echo "No changes in module1. Skipping deployment.";
      fi
  when: manual

include: "infrastructure/ci/**.yml"
