# Update n.0
.notification-service-build-vars:
  variables:
    MODULE_NAME: notification-service

.notification-service-build-changes:
  only:
    changes:
      - $MODULE_NAME/**/*
      - .gitlab-ci-notification-service.yml
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

build-notification-service:
  extends:
    - .notification-service-build-vars
    - .notification-service-build-changes
    - .build

docker-notification-service:
  extends:
    - .notification-service-build-vars
    - .notification-service-build-changes
    - .docker

deploy-notification-service:
  extends:
    - .notification-service-build-vars
    - .notification-service-build-changes
    - .deploy

