# Update n.0

stages:
  - maven
  - docker
  - deploy

cache:
  paths:
    - .m2/repository

.build:
  before_script:
    - echo "Start build $MODULE_NAME"
    - |
      cat <<EOF > settings.xml
      <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
              <server>
                  <id>gitlab-registry</id>
                  <username>${CI_REGISTRY_USER}</username>
                  <password>${CI_REGISTRY_PASSWORD}</password>
              </server>
          </servers>
      </settings>
      EOF
  stage: maven
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -s settings.xml -Dmaven.repo.local=.m2/repository -DskipTests=true clean package -pl $MODULE_NAME
  artifacts:
    paths:
      - $MODULE_NAME/target/*.jar
  tags:
    - dev
  allow_failure: true

.docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/$MODULE_NAME"
      --dockerfile "Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA"
  tags:
    - dev

.deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f ./infrastructure/docker/docker-compose-services-dev.yaml up -d $MODULE_NAME
  tags:
    - dev

include:
 - local: ".gitlab-ci-audit-service.yml"
 - local: ".gitlab-ci-authorization-server.yml"
 - local: ".gitlab-ci-comment-service.yml"
 - local: ".gitlab-ci-common.yml"
 - local: ".gitlab-ci-configuration-service.yml"
 - local: ".gitlab-ci-notification-service.yml"
 - local: ".gitlab-ci-post-service.yml"
 - local: ".gitlab-ci-processor-service.yml"
 - local: ".gitlab-ci-profile-service.yml"
 - local: ".gitlab-ci-proxy-service.yml"
 - local: ".gitlab-ci-storage-service.yml"
 - local: ".gitlab-ci-user-info-service.yml"
