# Update n.0

stages:
  - maven
  - docker
  - deploy

variables:
  CACHE_DIR: cache

cache:
  paths:
    - .m2/repository
    - ${CACHE_DIR}

.build:
  before_script:
    - echo "Start build $MODULE_NAME"
  stage: maven
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -s ci-cd-settings.xml -Dmaven.repo.local=.m2/repository -DskipTests=true clean package -pl $MODULE_NAME
  artifacts:
    paths:
      - $MODULE_NAME/target/*.jar
  tags:
    - dev
  allow_failure: true

.docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/$MODULE_NAME"
      --dockerfile "Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA"
      --cache=true 
      --cache-dir=$CACHE_DIR
  tags:
    - dev
  allow_failure: true
  when: manual

.deploy:
  image: docker:latest
  stage: deploy
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker-compose -f ./infrastructure/docker/docker-compose-services-dev.yaml up -d $MODULE_NAME
  tags:
    - dev
  allow_failure: true
  when: manual

include:
  - local: "audit-service/.gitlab-ci.yml"
  - local: "authorization-server/.gitlab-ci.yml"
  - local: "comment-service/.gitlab-ci.yml"
  - local: "common/.gitlab-ci.yml"
  - local: "configuration-service/.gitlab-ci.yml"
  - local: "notification-service/.gitlab-ci.yml"
  - local: "post-service/.gitlab-ci.yml"
  - local: "processor-service/.gitlab-ci.yml"
  - local: "profile-service/.gitlab-ci.yml"
  - local: "proxy-service/.gitlab-ci.yml"
  - local: "storage-service/.gitlab-ci.yml"
  - local: "user-info-service/.gitlab-ci.yml"
