# Update n.0
.profile-service-build-vars:
  variables:
    MODULE_NAME: profile-service

.profile-service-build-changes:
  only:
    changes:
      - $MODULE_NAME/**/*
      - .gitlab-ci-profile-service.yml
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

build-profile-service:
  extends:
    - .profile-service-build-vars
    - .profile-service-build-changes
    - .build

docker-profile-service:
  extends:
    - .profile-service-build-vars
    - .profile-service-build-changes
    - .docker

deploy-profile-service:
  extends:
    - .profile-service-build-vars
    - .profile-service-build-changes
    - .deploy

