variables:
  MODULE_NAME: common

.changes:
  only:
    refs:
      - .gitlab-ci-common.yml

common-build:
  extends:
    - .build

deploy:
  stage: deploy
  image: maven:3.8.4-openjdk-17-slim
  script:
    - cp ci-settings.xml $HOME/.m2/settings.xml
    - mvn deploy
  tags:
    - dev