# Update n.0
.storage-service-build-vars:
  variables:
    MODULE_NAME: storage-service

.storage-service-build-changes:
  only:
    changes:
      - $MODULE_NAME/**
      - .gitlab-ci-storage-service.yml
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

build-storage-service:
  extends:
    - .storage-service-build-vars
    - .storage-service-build-changes
    - .build

docker-storage-service:
  extends:
    - .storage-service-build-vars
    - .storage-service-build-changes
    - .docker

deploy-storage-service:
  extends:
    - .storage-service-build-vars
    - .storage-service-build-changes
    - .deploy

