# Update n.0
.configuration-service-build-vars:
  variables:
    MODULE_NAME: configuration-service

.configuration-service-build-changes:
  only:
    changes:
      - $MODULE_NAME/**
      - .gitlab-ci-configuration-service.yml
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

build-configuration-service:
  extends:
    - .configuration-service-build-vars
    - .configuration-service-build-changes
    - .build

docker-configuration-service:
  extends:
    - .configuration-service-build-vars
    - .configuration-service-build-changes
    - .docker

deploy-configuration-service:
  extends:
    - .configuration-service-build-vars
    - .configuration-service-build-changes
    - .deploy

