variables:
  MODULE_NAME: ""

.changes:
  only:
    refs:
      - branches
    changes:
      - $MODULE_NAME/*

stages:
  - maven
  - docker
  - deploy

maven:
  extends:
    - .changes
  stage: maven
  image: maven:3.8.4-openjdk-17-slim
  script:
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -DskipTests=true clean package -pl $MODULE_NAME
  tags:
    - dev

docker:
  extends:
    - .changes
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/$MODULE_NAME/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA"
  tags:
    - dev

deploy:
  extends:
    - .changes
  stage: deploy
  script:
    - if [ "$CI_PIPELINE_SOURCE" == "push" ] && git diff --name-only $CI_COMMIT_BEFORE_SHA..$CI_COMMIT_REF_NAME | grep --quiet module1/; then
      cd $MODULE_NAME;
      ls
      else
      echo "No changes in module1. Skipping deployment.";
      fi

include:
  - ".gitlab-ci-audit.yml"
