apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-service
  labels:
    app: processor-service
spec:
  template:
    metadata:
      name: processor-service
      labels:
        app: processor-service
    spec:
      containers:
        - name: processor-service
          image: ghcr.io/chahirchalouati/processor-service:2
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{
              "spring.cloud.config.uri": "http://configuration-service:8888",
              "spring.data.mongodb.host": "mongodb",
              "spring.data.mongodb.port": "27017",
              "spring.profiles.active":"prod"
              }'
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey2
  selector:
    matchLabels:
      app: processor-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: processor-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: processor-service
  minReplicas: 1
  maxReplicas: 4
---
apiVersion: v1
kind: Service
metadata:
  name: processor-service
spec:
  selector:
    app: processor-service
  ports:
    - port: 9000
      targetPort: 9000
  type: LoadBalancer