apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  labels:
    app: configuration-service
spec:
  template:
    metadata:
      name: configuration-service
      labels:
        app: configuration-service
    spec:
      containers:
        - name: configuration-service
          image: ghcr.io/chahirchalouati/configuration-service:2
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"spring.profiles.active":"prod"}'
      restartPolicy: Always
      imagePullSecrets:
        - name: myregistrykey2
  selector:
    matchLabels:
      app: configuration-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: configuration-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: configuration-service
  minReplicas: 1
  maxReplicas: 4
---
apiVersion: v1
kind: Service
metadata:
  name: configuration-service
spec:
  selector:
    app: configuration-service
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer