version: '3.3'
services:

  configuration-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.profiles.active":"docker"
      }'
    ports:
      - '8888:8888'
    networks:
      - l_net

  audit-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '7003:7003'
    networks:
      - l_net

  authentication-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
        "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
    ports:
      - '9000:9000'
    networks:
      - l_net

  post-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
         "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '7005:7005'
    networks:
      - l_net

  proxy-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
         "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '9999:9999'
    networks:
      - l_net

  notification-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
         "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '7008:7008'
    networks:
      - l_net

  storage-service:
    image: ${CI_REGISTRY_IMAGE}/$MODULE_NAME:$CI_COMMIT_SHORT_SHA
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.cloud.config.uri": "http://configuration-service:8888",
         "spring.profiles.active":"docker"
      }'
    depends_on:
      - configuration-service
      - authentication-service
    ports:
      - '7010:7010'
    networks:
      - l_net

networks:
  l_net:
    driver: bridge

volumes:
  mysql-db:
  postgres-db:
  cassandra-db:
  mongo-db:
  minio:
  elasticsearch-db:
  rabbit-log:
  rabbit-conf:
  nodemodules:
