server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            filter: INFO
spring:
  application:
    name: configuration-service
---
spring:
  config:
    activate:
      on-profile: docker, prod
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/chehhhir/gramify-ms-configurations.git
          default-label: main
          force-pull: true
          refresh-rate: 5

---
spring:
  config:
    activate:
      on-profile: native,dev
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/IdeaProjects/gramify-ms-configurations