# Update n.0

stages:
  - maven

variables:
  CACHE_DIR: docker-cache
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --settings ci_settings.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true



cache:
  paths:
    - .m2/repository
    - ${CACHE_DIR}

.changes:
  only:
    changes:
      - common/**
      - .gitlab-ci.yml

.build:
  extends: .changes
  before_script:
    - echo "Start build common"
  stage: maven
  image: maven:3.9.3-eclipse-temurin-20
  script:
    - if [ ! -f ci_settings.xml ]; then
      echo "CI settings missing";
      fi
    - mvn $MAVEN_CLI_OPTS $MAVEN_OPTS clean package -pl "common"
  artifacts:
    paths:
      - common/target/*.jar
  tags:
    - dev
  allow_failure: true

.docker:
  extends: .changes
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/common"
      --dockerfile "Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/common:$CI_COMMIT_SHORT_SHA"
      --cache=true
      --cache-dir=$CACHE_DIR
  tags:
    - dev
  allow_failure: true
  when: manual