# Update n.0
.changes:
  only:
    changes:
      - $MODULE_NAME/**
      - .gitlab-ci-common.yml
      - .gitlab-ci.yml

infrastructure-build:
  variables:
    MODULE_NAME: infrastructure
  extends:
    - .build

infrastructure-docker:
  variables:
    MODULE_NAME: infrastructure
  extends:
    - .docker

infrastructure-deploy:
  variables:
    MODULE_NAME: infrastructure
  extends:
    - .deploy

